### ISSUE TITLE
Load balancing for browserchannel 

### ISSUE THREAD

**Issue by murugan-pandian** [josephg/node-browserchannel#51]
If any way to Load balancing for browserchannel like socket.io (redis adapter)

**Comment by wenzowski** [comment]
@murugannode if you run nginx 1.7.x mainline (currently tracking commercial distro) all you need is

```nginx
upstream {
  hash $arg_a consistent;
}
```

You can customize your affinity arg to avoid conflict with your app, eg `hash $arg_noconflictAffinity consistent;` per #43. While nginx instances share the same configured upstream set, AWS LB cookie-stickiness should not be necessary as [libketama](https://github.com/RJ/ketama) will route to the same upstream no matter which nginx instance your lb routes requests to.

YMMV
