### ISSUE TITLE
'connect' missing from package.json?

### ISSUE THREAD

**Issue by mrft** [josephg/node-browserchannel#53]

**Comment by 3rd-Eden** [comment]
This module isn't using connect, so it's not missing.

**Comment by mrft** [comment]
Well it complains about it when trying to run the first thing from the readme file: 


Run the example server with:
<pre>
# coffee node_modules/share/examples/server.coffee
</pre>

**Comment by 3rd-Eden** [comment]
Thats because the example uses connect, not the actual module.
