### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by curran** [josephg/node-browserchannel#61]
Greetings,

This seems like a really nice rock solid and lightweight alternative to Socket.io that is compatible with ShareDB.

The most recent release includes `connect` as a dependency, which has subsequently been removed from `package.json`.

Are there any plans to publish a new release to NPM with the updates that have transpired since 2014?

**Comment by josephg** [comment]
Sure I can do that! Want to write up a PR?

**Comment by curran** [comment]
@josephg Awesome!

I believe all you'd need to do is run the following:

```
# Bump the minor version (will modify package.json and make a commit for you)
npm version minor
# Publish to NPM
npm publish
# Push the updated package.json to the repo
git push
# Update release tags to GitHub
git push --tags
```

I don't believe any content inside the repo needs to be changed, but if you'd like me to change something please let me know what changes should be made and I'd be happy to submit up a PR.

Also, thanks for your new note in the README on wide WebSockets support - that's a great point!

**Comment by reem** [comment]
@josephg bump here, can you make a new release with the changes that were just merged? The above instructions should be accurate.

**Comment by josephg** [comment]
```
$ git push && git push --tags && npm publish
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 892 bytes | 0 bytes/s, done.
Total 9 (delta 7), reused 0 (delta 0)
remote: Resolving deltas: 100% (7/7), completed with 5 local objects.
To github.com:josephg/node-browserchannel.git
   887b2c4..2be5bdb  master -> master
Counting objects: 1, done.
Writing objects: 100% (1/1), 157 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To github.com:josephg/node-browserchannel.git
 * [new tag]         v2.1.0 -> v2.1.0
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> browserchannel@2.1.0 prepublish /Users/josephg/src/node-browserchannel
> make dist/server.js

make: `dist/server.js' is up to date.
+ browserchannel@2.1.0
```
